#!/usr/bin/bash

if  ( grep  "$*" < phone-book); then 
echo -n

else 
echo "Entered name was not found."
fi
echo "Would you like to:"
echo "1. Search for a different name."
echo "2. Terminate program"


read input
if [ $input == 1 ]; then
echo "Please enter new search term."
read term
bash $0 $term
else
echo "Terminating program."

fi

